if(NOT DEFINED CDDP_BINARY_DIR OR NOT DEFINED CDDP_SOURCE_DIR)
  message(FATAL_ERROR "CDDP_BINARY_DIR and CDDP_SOURCE_DIR must be provided")
endif()

set(SMOKE_ROOT "${CDDP_BINARY_DIR}/package_smoke")
set(SMOKE_PREFIX "${SMOKE_ROOT}/install")
set(CONSUMER_SOURCE_DIR "${CDDP_SOURCE_DIR}/tests/package_smoke")
set(CONSUMER_BUILD_DIR "${SMOKE_ROOT}/consumer-build")

file(REMOVE_RECURSE "${SMOKE_ROOT}")
file(MAKE_DIRECTORY "${SMOKE_ROOT}")

execute_process(
  COMMAND "${CMAKE_COMMAND}" --install "${CDDP_BINARY_DIR}" --prefix "${SMOKE_PREFIX}"
  RESULT_VARIABLE INSTALL_RESULT
  OUTPUT_VARIABLE INSTALL_STDOUT
  ERROR_VARIABLE INSTALL_STDERR
)
if(NOT INSTALL_RESULT EQUAL 0)
  message(FATAL_ERROR "PackageInstallSmoke install failed:\n${INSTALL_STDOUT}\n${INSTALL_STDERR}")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -S "${CONSUMER_SOURCE_DIR}" -B "${CONSUMER_BUILD_DIR}"
          -DCMAKE_BUILD_TYPE=Release
          "-DCMAKE_PREFIX_PATH=${SMOKE_PREFIX}"
  RESULT_VARIABLE CONFIGURE_RESULT
  OUTPUT_VARIABLE CONFIGURE_STDOUT
  ERROR_VARIABLE CONFIGURE_STDERR
)
if(NOT CONFIGURE_RESULT EQUAL 0)
  message(FATAL_ERROR "PackageInstallSmoke configure failed:\n${CONFIGURE_STDOUT}\n${CONFIGURE_STDERR}")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" --build "${CONSUMER_BUILD_DIR}" --parallel 4
  RESULT_VARIABLE BUILD_RESULT
  OUTPUT_VARIABLE BUILD_STDOUT
  ERROR_VARIABLE BUILD_STDERR
)
if(NOT BUILD_RESULT EQUAL 0)
  message(FATAL_ERROR "PackageInstallSmoke build failed:\n${BUILD_STDOUT}\n${BUILD_STDERR}")
endif()
