name: C++ CI

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test with LibTorch CPU and GPU
        include:
          - torch: "ON"
            torch_gpu: "ON" 
          - torch: "ON"
            torch_gpu: "OFF" 

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends cuda-toolkit-12-4 # Install CUDA Toolkit 

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCDDP-CPP_BUILD_TESTS=ON \
          -DCDDP-CPP_TORCH=${{ matrix.torch }} \
          -DCDDP-CPP_TORCH_GPU=${{ matrix.torch_gpu }} \

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -V
