name: C++ CI

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test with and without LibTorch CPU and GPU
        include:
          - gurobi: "OFF"
            torch: "ON"
            torch_gpu: "ON"
          - gurobi: "OFF"
            torch: "ON"
            torch_gpu: "OFF" 

    steps:
    - uses: actions/checkout@v3

    - name: Install Gurobi (if needed)
      if: matrix.gurobi == 'ON'
      run: |
        # Replace this with the actual installation instructions for your Gurobi version
        wget -O gurobi.sh https://packages.gurobi.com/11.0/gurobi11.0.0_linux64.tar.gz 
        chmod +x gurobi.sh
        sudo ./gurobi.sh
        # You might need to accept the license agreement interactively or by modifying the script
        # Ensure Gurobi is in the PATH or set GUROBI_ROOT appropriately

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ${{{{ matrix.torch == 'ON' && matrix.torch_gpu == 'ON' ? 'cuda' : '' }}}}  # Install CUDA if needed

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCDDP-CPP_GUROBI=${{ matrix.gurobi }} \
          -DCDDP-CPP_BUILD_TESTS=ON \
          -DCDDP-CPP_TORCH=${{ matrix.torch }} \
          -DCDDP-CPP_TORCH_GPU=${{ matrix.torch_gpu }} \
          ${{ matrix.gurobi == 'ON' ? '-DGUROBI_ROOT=/opt/gurobi' : '' }}  # Adjust GUROBI_ROOT if necessary

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -V
